[project]
name = "task-tracker"
version = "0.0.1"
description = "A simple command line interface (CLI) to track what you need to do, what you have done, and what you are currently working on"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "prettytable>=3.16.0",
]
